### ISSUE TITLE
mkbgp: Sporadic exceptions

### ISSUE THREAD

**Issue by jplitza** [freifunk/icvpn-scripts#44]
Since merging #40, I seldom (once a week maybe? The script runs hourly) get tracebacks like the following from one of the five servers that run it (although different ones every time):

```
Exception in thread Thread-67 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
  File "/usr/lib/python2.7/threading.py", line 763, in run
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 102, in worker
  File "/usr/lib/python2.7/Queue.py", line 179, in get
  File "/usr/lib/python2.7/threading.py", line 384, in notifyException in thread Thread-95 (most likely raised during interpreter shutdown):

<type 'exceptions.TypeError'>: 'NoneType' object is not callable
Exception in thread Thread-24 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
  File "/usr/lib/python2.7/threading.py", line 763, in run
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 102, in worker
  File "/usr/lib/python2.7/Queue.py", line 179, in get
  File "/usr/lib/python2.7/threading.py", line 384, in notify
<type 'exceptions.TypeError'>: 'NoneType' object is not callable
Exception in thread Thread-74 (most likely raised during interpreter shutdown):
Traceback (most recent call last):Traceback (most recent call last):

  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
  File "/usr/lib/python2.7/threading.py", line 763, in run
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 102, in worker
  File "/usr/lib/python2.7/Queue.py", line 179, in get
  File "/usr/lib/python2.7/threading.py", line 384, in notify
<type 'exceptions.TypeError'>: 'NoneType' object is not callable

  File "/usr/lib/python2.7/threading.py", line 763, in run
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 102, in worker
  File "/usr/lib/python2.7/Queue.py", line 179, in get
  File "/usr/lib/python2.7/threading.py", line 384, in notify
<type 'exceptions.TypeError'>: 'NoneType' object is not callable
```

Any idea what causes them?

**Comment by Ranlvor** [comment]
Perhaps it has anything todo with the multihreading needed to scan for open BGP-Ports without having to wait to long.

You could try to patch the skript to use less threads by replacing:
https://github.com/freifunk/icvpn-scripts/blob/master/mkbgp#L97
```Python
Pool(len(peers)).map(update_peer_passive, peers)
```
to something like
```Python
Pool(len(peers)/16).map(update_peer_passive, peers)
```

This should take about 16 times as long but only 1/16th of the threads.
